import {renderProgrammeReview, renderProgressVerification, renderTIA} from './training-section.mjs';

// Companion studies reuse the same evidence and calculations as the deck appendix.
export function renderStudyPage(p, h) {
  const {training, model, table, esc, eyebrow, button, link, figure, metric, contact, external} = h;
  const ctx = {training, model, table, esc};
  const isReview = p.study === 'review';
  const pdf = '/downloads/' + p.presentation;
  const reviewRoute = '/projects/contractor-schedule-review/';
  const tiaRoute = '/projects/illustrative-time-impact-analysis/';
  const sections = isReview
    ? [['brief','Review brief'],['findings','Findings'],['progress','Progress'],['decision','Review decision']]
    : [['brief','Analysis basis'],['comparison','Before / after'],['analysis','Fragnet & calculation'],['decision','Interpretation']];
  const date = value => new Date(value+'T00:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
  const intro = `<section class="case-hero"><div class="container">${link('/projects/','All case studies','back-link')}${eyebrow('CASE STUDY '+esc(p.number)+' / TRAINING EXERCISE')}<h1>${isReview?'Contractor<br>Schedule Review.':'Delay Analysis<br>&amp; TIA.'}</h1><p class="case-subtitle">${esc(p.subtitle)}</p><div class="case-meta"><span>Companion to the P6 portfolio</span><span>Independent training exercise</span><span>Presentation slides ${esc(p.slides)}</span></div><div class="button-row">${button(pdf+'#page='+p.startPage,'View Supporting Slides',false,external)}${button('/downloads/'+p.powerpoint,'Download PowerPoint',true,'download')}</div></div></section><div class="case-nav"><nav class="container" aria-label="Case study sections">${sections.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')}</nav></div>`;
  const brief = `<section class="section container" id="brief">${eyebrow('01 / THE ASSIGNMENT')}<h2>${isReview?'From a schedule finding<br>to a review action.':'Measure the time effect.<br>Explain the assumptions.'}</h2><p class="lead">${esc(p.summary)}</p><aside class="source-note"><strong>${esc(training.disclosure)}</strong> ${isReview?'The calendar and network findings come from the existing simulated building programme. Review comments, owners, deadlines and the quantity-progress example are training material.':'This is a separate miniature CPM model, developed as a teaching companion to the building programme. It does not change the original P6 forecast or represent another client project.'}</aside><div class="metric-grid">${isReview?metric('1,206','Activities in source programme')+metric('4','Selected review comments','No overall acceptance score')+metric('40%','Verified package progress','Assumed slab package only')+metric('−10 pp','Variance against plan','Physical quantity basis'):metric(model.before.duration+' → '+model.after.duration,'Remaining working days')+metric('+'+model.workingImpact,'Working-day impact')+metric('+'+model.calendarImpact,'Calendar-day impact')+metric(esc(training.tia.milestone),'Training handover','Same milestone in both cases')}</div><div class="method-grid"><article><span>01</span><h3>${isReview?'Confirm the basis':'Freeze the pre-event update'}</h3><p>${isReview?'Record the data date, schedule version, baseline and calendar assumptions before comparing reports.':'Use the same data date, logic, calendar and milestone in both calculations. Prior enabling work is assumed complete.'}</p></article><article><span>02</span><h3>${isReview?'Separate evidence from queries':'Insert the assumed event'}</h3><p>${isReview?'A diagnostic prompts an explanation; it does not by itself prove faulty logic or a delay entitlement.':'Add the four-working-day design clarification before installation; retain the parallel documentation path.'}</p></article><article><span>03</span><h3>${isReview?'Issue traceable actions':'Compare and qualify'}</h3><p>${isReview?'State the issue, requested evidence, owner, response date and closure condition.':'Measure movement of the handover milestone, then explain what the model establishes and what needs contract evidence.'}</p></article></div></section>`;
  const findings = isReview ? `<section class="section muted-section" id="findings"><div class="container">${eyebrow('02 / PROGRAMME REVIEW')}<h2>A focused review register.</h2><p class="lead">Saved update at 01 Apr 2027. Findings below are traceable to slides 9 and 12 of the presentation; the review actions are proposed training responses.</p>${table(['ID / topic','Source finding','Review comment / requested evidence'],[
    ['C-01 / Calendar','No holiday exceptions for 2026–2028.','Confirm the agreed working and shutdown calendar. Recalculate a copy before quantifying completion impact.'],
    ['L-01 / Logic','112 positive lags; 12 activities with SS-only successors.','Explain the construction basis for lags and demonstrate finish logic for the flagged activities. These counts alone do not prove an error.'],
    ['F-01 / Float','496 incomplete activities above 44 own-calendar working days of float.','Review scope interfaces and successor completeness. This diagnostic threshold is not a DCMA compliance result.'],
    ['B-01 / Baseline','Seven of eight original ground-floor report baseline rows differ from the embedded baseline.','Confirm the approved comparison source and regenerate the report. Use the corrected milestone comparison in slide 9.']
  ],'Selected contractor programme review comments — training register')}${figure('schedule-audit.webp','Source evidence: schedule quality findings in the existing P6 presentation, slide 12.',p.presentation,'Schedule quality review slide from the simulated P6 building project','slide-figure')}${renderProgrammeReview(ctx)}<details class="method-details"><summary>Close-out requirements</summary><p>Retain the original submission. Log the contractor response, approved calendar and baseline reference. Compare the revised calculation to the same handover milestone and record any new logic or setting changes. Close the comment only when the evidence answers the query; no response or completed P6 rerun is supplied in this exercise.</p></details></div></section><section class="section container" id="progress">${eyebrow('03 / PROGRESS VERIFICATION')}<h2>Reported work needs<br>a measurement basis.</h2>${renderProgressVerification(ctx)}</section>` : `<section class="section muted-section" id="comparison"><div class="container">${eyebrow('02 / BEFORE AND AFTER')}<h2>Compare the same handover.</h2><p class="lead">M-TR01 moves from ${date(model.before.handover)} to ${date(model.after.handover)}, at 17:00 in both cases.</p><div class="tia-comparison" aria-label="Remaining controlling-chain duration, working days"><div class="tia-comparison-row"><h3>Pre-event update <span>${model.before.duration} working days</span></h3><div class="tia-bar" style="--total:${model.after.duration}"><span class="tia-install" style="--days:${training.tia.installationDays}">Installation · ${training.tia.installationDays}d</span><span class="tia-test" style="--days:${training.tia.testingDays}">Test · ${training.tia.testingDays}d</span></div><p>Release → installation → testing → M-TR01</p></div><div class="tia-comparison-row"><h3>With inserted event <span>${model.after.duration} working days</span></h3><div class="tia-bar" style="--total:${model.after.duration}"><span class="tia-event" style="--days:${training.tia.eventDays}">Event · ${training.tia.eventDays}d</span><span class="tia-install" style="--days:${training.tia.installationDays}">Installation · ${training.tia.installationDays}d</span><span class="tia-test" style="--days:${training.tia.testingDays}">Test · ${training.tia.testingDays}d</span></div><p>Release → design clarification → installation → testing → M-TR01</p></div></div><p class="fine-print">Bars show working duration, not a calendar-date axis. In both models, an unchanged ${training.tia.documentationDays}-working-day documentation path runs from release to handover in parallel.</p></div></section><section class="section container" id="analysis">${eyebrow('03 / THE ANALYSIS')}<h2>Logic, dates and interpretation.</h2>${renderTIA(ctx)}</section>`;
  const decision = `<section class="section muted-section" id="decision"><div class="container">${eyebrow('04 / THE REVIEW CONCLUSION')}<h2>${isReview?'Keep unresolved queries visible.':'A modelled impact,<br>with a defined boundary.'}</h2><p class="large-copy">${isReview?'The exercise leaves the calendar query open pending evidence. The assumed slab package is 10 percentage points below plan, while 20 m³ of reported work still needs verification. These are separate findings requiring separate actions.':'Under the stated assumptions, the inserted event moves M-TR01 by four working days. This supports a time-impact discussion; contractual entitlement still depends on the governing contract, event responsibility and records.'}</p>${table(['What this demonstrates','What remains to be established'],isReview?[
    ['A review comment connected to an observed schedule finding.','An agreed calendar and a native schedule recalculation before stating a time impact.'],
    ['Quantity-based progress and an owner/action/deadline register.','Actual measurement records, acceptance evidence and the recovery proposal.'],
    ['Consistent milestone and baseline comparisons.','Formal programme acceptance under the project’s own review procedure.']
  ]:[
    ['Controlled before/after comparison of a single assumed event.','Event responsibility, notices and supporting records under the governing contract.'],
    ['Parallel-path float is considered in the miniature model.','Actual concurrency, mitigation, resource limits and the relevant update at the event date.'],
    ['Working days and elapsed calendar days are distinguished.','Any EOT entitlement or compensation assessment.']
  ],'Conclusions and evidence still required')}<p class="fine-print">${isReview?'This page uses the existing P6 case study and its training appendix. It is not a separate employment assignment.':'Introductory knowledge of FIDIC-based contract procedures is discussed within the exercise. No specific form, edition, clause or notice period is assumed.'}</p><div class="button-row">${button(isReview?tiaRoute:reviewRoute,isReview?'Next: Delay Analysis & TIA':'Explore Contractor Schedule Review')}${button('/projects/primavera-p6-project-controls/','Original P6 Case Study',true)}</div><div class="case-download"><div>${eyebrow('SUPPORTING PRESENTATION')}<h2>Read it with the source material.</h2><p>Slides ${esc(p.slides)} in the shared 18-slide portfolio. The PowerPoint includes speaker notes explaining the exercise and its assumptions.</p></div><div class="button-row">${button(pdf+'#page='+p.startPage,'View Supporting Slides',false,external)}${button('/downloads/'+p.powerpoint,'Download PowerPoint',true,'download')}</div></div></div></section>`;
  return '<div class="companion-study">' + intro + brief + findings + decision + '</div>' + contact();
}

// Native SVG cover: an exact illustration of the teaching model, not project evidence.
export function tiaCover(training, model) {
  const date = value => new Date(value+'T00:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'});
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900" role="img" aria-labelledby="title desc"><title id="title">Illustrative time impact analysis</title><desc id="desc">Training handover moves from ${date(model.before.handover)} to ${date(model.after.handover)}. Impact: ${model.workingImpact} working days and ${model.calendarImpact} calendar days.</desc><rect width="1600" height="900" fill="#f1f4f6"/><path d="M90 140h1420" stroke="#ccd6dc" stroke-width="2"/><g font-family="Arial, sans-serif" fill="#102332"><text x="90" y="104" font-size="27" letter-spacing="3">03 / DELAY ANALYSIS · TRAINING EXERCISE</text><text x="90" y="266" font-size="76" font-weight="600">One event.</text><text x="90" y="358" font-size="76" font-weight="600">A traceable time impact.</text><text x="90" y="490" font-size="25" fill="#53636d">PRE-EVENT HANDOVER</text><text x="865" y="490" font-size="25" fill="#53636d">WITH INSERTED EVENT</text><text x="90" y="565" font-size="58">${date(model.before.handover)}</text><text x="865" y="565" font-size="58">${date(model.after.handover)}</text><path d="M685 537h100m-24-16 24 16-24 16" fill="none" stroke="#967244" stroke-width="4"/><text x="90" y="705" font-size="46" fill="#967244">+${model.workingImpact} working days / +${model.calendarImpact} calendar days</text><text x="90" y="813" font-size="25" fill="#53636d">Assumed event · miniature CPM · not a live contractual claim</text></g></svg>`;
}
